### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by xndrxw** [pinkywafer/sonoff_rf_bridge-esphome#1]
I have tried to compile a few times now and keep getting this error message. Any idea what this could be caused by?

ESPAsyncTCP.cpp:(.text._ZN11AsyncClient9onTimeoutESt8functionIFvPvPS_jEES1_+0x8): multiple definition of `AsyncClient::onTimeout(std::function<void (void*, AsyncClient*, unsigned int)>, void*)'
/data/sonoff_rf/.pioenvs/sonoff_rf/libf28/libESPAsyncTCP_ID305.a(ESPAsyncTCP.cpp.o):ESPAsyncTCP.cpp:(.text._ZN11AsyncClient9onTimeoutESt8functionIFvPvPS_jEES1_+0x8): first defined here
collect2: error: ld returned 1 exit status
*** [/data/sonoff_rf/.pioenvs/sonoff_rf/firmware.elf] Error 1

**Comment by zvldz** [comment]
https://github.com/esphome/issues/issues/683

**Comment by xndrxw** [comment]
> [esphome/issues#683](https://github.com/esphome/issues/issues/683)

I was able to get it working by using the esphome dev release.
